import type { Metadata } from "next";
import "./globals.css";
import "@/styles/style.css"
import Providers from "./Providers";
import { poppins } from "@/fonts";
import HeadingBar from "@/components/Navigation/Header";
import Footer from "@/components/footer/Footer";
import AuthListener from "@/components/auth/AuthListener";

export const metadata: Metadata = {
  title: "Flash Kanji | Your Kanji Learning Companion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased text-dark`}
      >
        <Providers>

          <AuthListener/>
          {children}

        </Providers>
      </body>
    </html>
  );
}
