import type { Metadata } from "next";
import "./globals.css";
import "@/styles/style.css"
import Providers from "./Providers";
import { poppins } from "@/fonts";
import { Toaster } from 'sonner'

import AuthListener from "@/components/auth/AuthListener";
import SessionSync from "@/components/session-sync";
import CookieConsent from "@/components/cookie-consent";

export const metadata: Metadata = {
  title: "Flash Kanji | Your Kanji Learning Companion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Analytics
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-DFN1W13SY3"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-DFN1W13SY3');
            `,
          }}
        /> */}
      </head>
      <body
        className={`${poppins.className} min-h-screen antialiased text-dark dark:text-gray-100  dark:bg-[#1A2027]`}
      >
        <Providers>
          <SessionSync />
          <AuthListener />
          <Toaster position="top-right" richColors />
          {children}
          <CookieConsent />
        </Providers>
      </body>
    </html>
  );
}
